purepursuit_node:
  double_car: false
  # double_car: true
  lookahead_distance: 0.2
  safe_topic: "/safe"
  odom_topic: "/mavros/vision_pose/pose"
  path_topic: "/car1_astar_path_o"
  cmd_vel_topic: "/ctrl_cmd"
  stop_flag_topic: "/stop_flag"
  yaw_error_max_threshold: 5.0   #单位 度,超过这个值开始调整
  yaw_error_min_threshold: 2.0   #单位 度,小于这个值停止调整
  stop_duration_time_: 1.5        #停止持续时间
  max_angular_z_: 15.0              #调整yaw角的最大角速度  degree/s
  kp_yaw_: 0.8
  ki_yaw_: 0.01
  kd_yaw_: 0.1
  vehicle_max_speed: 0.3
  vehicle_avg_speed: 0.28

